name: Push to another repo to deploy to Vercel

on:
  push:
    branches: [main, feature/moviedbapi]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install dependencies (if needed for build script)
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          gem install mustache

      - name: Run build script
        run: sh ./build.sh

      - name: Push output to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: 'hiwon-lee' # <- 여기에 대상 사용자 이름
          destination-repository-name: 'next-netflix-20th' # <- 여기에 대상 리포지토리 이름
          user-email: ${{ secrets.GIT_EMAIL }}
          user-name: ${{ secrets.GIT_USERNAME }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Test the output directory variable
        run: echo $DESTINATION_CLONED_DIRECTORY
